### ISSUE TITLE
Timing

### ISSUE THREAD

**Issue by korbinian90** [korbinian90/QuantitativeSusceptibilityMappingTGV.jl#2]
The code is currently about 20x slower than the Cython version.

Points where to look:
- Julia code needs to be type-stable (check with @code_warntype function(inputs))
- Julia runs single-threaded, Cython has 8 cores / 16 threads

**Comment by korbinian90** [comment]
Quick test of the package ParallelStencil.jl:
- kernel code can be nearly identical
- 30% speedup on CPU (similar to Cython)
- 2x speedup on GPU (~10x compared to Cython CPU)
- only tested with tgv_update_eta, 500 iterations, rest was commented out

**Comment by korbinian90** [comment]
**speedup** 
- it seems fine to only do calculation for voxels inside the mask
- in st version: if CENTER

**Comment by korbinian90** [comment]
**new version using ParallelStencil.jl timing**
1000 iterations
Cython: 320s
julia CPU stencil: 180s
julia GPU stencil: 20s
**create rectangular mask and only compute inside**
This is a data specific improvement, in this test case 55% of the image was cut away
julia CPU stencil+mask: 80s
julia GPU stencil+mask: 10s

**Comment by stebo85** [comment]
That's so cool!
